"""password_hash

Revision ID: 350888df6a87
Revises: 9802a08a6bdc
Create Date: 2023-05-20 12:15:56.489807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350888df6a87'
down_revision = '9802a08a6bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=False))
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
